### ISSUE TITLE
Type object is not subscriptable

### ISSUE THREAD

**Issue by Vessel-Legends** [ArdenButterfield/stammer#73] opened 2023-05-08 01:13 UTC
For reference, I am running python 3.8.6, is there another python version I need to install?

![image](https://user-images.githubusercontent.com/79474598/236713384-fcbed328-1e56-496f-9e68-a43c846c307c.png)

**Comment by GarfQC** [comment] 2023-08-23 01:45
I'm having the same issue here, but on Python 3.7.1.

**Comment by cabfile** [comment] 2023-09-18 11:52
same issue here, 3.8.10

**Comment by Firepal** [comment] 2023-12-27 01:26
Type annotations were added for pure readability purposes and are only supported by newer Python versions... This issue has come up before. I will have to remove them

**Comment by Firepal** [comment] 2023-12-27 01:32
@ArdenButterfield Considering you've kinda moved on from this project, could I be added as a maintainer on this repo?

**Comment by ArdenButterfield** [comment] 2023-12-27 05:04
@Firepal yes, absolutely! Sorry I haven't put any work into it all these months. I've had some ideas but have been caught up in other stuff. I sent you a collaborator invite (hope that gives you the necessary permissions) and sent you an email.

**Comment by Firepal** [comment] 2023-12-27 14:05
Duplicate of #66

**Closed by Firepal** 2023-12-27 14:05 UTC

**Comment by Firepal** [comment] 2023-12-27 16:54
> @ArdenButterfield Sorry I haven't put any work into it all these months. I've had some ideas but have been caught up in other stuff.

No worries pal. Same boat, I did a bunch of things this year.
